const SPACE_CHANNEL_PREFIX = '_ably_space_';

const CURSOR_UPDATE = 'cursorUpdate';
const LOCATION_UPDATE = 'locationUpdate';
const MEMBERS_UPDATE = 'membersUpdate';

const OUTGOING_BATCH_TIME_DEFAULT = 100;
const PAGINATION_LIMIT_DEFAULT = 5;

export {
  SPACE_CHANNEL_PREFIX,
  CURSOR_UPDATE,
  LOCATION_UPDATE,
  MEMBERS_UPDATE,
  OUTGOING_BATCH_TIME_DEFAULT,
  PAGINATION_LIMIT_DEFAULT,
};
