const SPACE_CHANNEL_PREFIX = '_ably_space_';

const CURSOR_UPDATE = 'cursor_update';

const OUTGOING_BATCH_TIME_DEFAULT = 100;
const INCOMING_BATCH_TIME_DEFAULT = 1;
const PAGINATION_LIMIT_DEFAULT = 5;

export {
  SPACE_CHANNEL_PREFIX,
  CURSOR_UPDATE,
  OUTGOING_BATCH_TIME_DEFAULT,
  INCOMING_BATCH_TIME_DEFAULT,
  PAGINATION_LIMIT_DEFAULT,
};
